---
redis_version: redis-6.2.5
redis_url: https://mirrors.wizcreative.com.cn/{{ redis_version }}.tar.gz
redis_root_dir: /usr/local/redis
redis_data_dir: /var/lib/redis
redis_log_dir: /data/logs/redis
redis_run_dir: /var/run/redis
redis_service: redis