---
- name: Upload Init
  copy:
    src: "files/init_centos.sh"
    dest: "/opt/init_centos.sh"
    owner: root
    group: root
    mode: 0755
    force: yes
  when: ansible_os_family == "RedHat"  

- name: Upload Init
  copy:
    src: "files/init_ubuntu.sh"
    dest: "/opt/init_ubuntu.sh"
    owner: root
    group: root
    mode: 0755
    force: yes
  when: ansible_os_family == "Debian"   

- name: Initialize
  shell: |
    /usr/bin/bash /opt/init_ubuntu.sh
  when: ansible_os_family == "Debian" 

- name: Initialize
  shell: |
    /usr/bin/bash /opt/init_centos.sh
  when: ansible_os_family == "RedHat"

- name: Update apt cache
  apt:
    update_cache: yes 
  when: ansible_os_family == "Debian"   

- name: Install dependencies
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - openssl
    - ca-certificates
    - libbz2-dev
    - libxml2-dev
    - libjpeg-dev
    - libssl-dev
    - libpng-dev
    - libfreetype6-dev
    - libcurl4-openssl-dev
    - libzip-dev
    - libsqlite3-dev
    - libgmp3-dev
    - make
    - mcrypt
    - libonig-dev
    - libreadline-dev
    - libxslt1-dev
    - curl
    - libffi-dev
    - gcc
    - g++
    - libsodium-dev
    - build-essential
    - libcurl3-openssl-dev
    - libmagickcore-dev
    - libmagickwand-dev
    - pkg-config
  ignore_errors: true
  when: ansible_os_family == "Debian" 

- name: Install dependencies RedHat
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - libsqlite3x-devel
    - libxml2 
    - libxml2-devel 
    - openssl 
    - openssl-devel 
    - libcurl 
    - libcurl-devel 
    - libjpeg 
    - libjpeg-devel 
    - libpng 
    - libpng-devel 
    - freetype 
    - freetype-devel 
    - php-mcrypt 
    - libmcrypt 
    - libmcrypt-devel 
    - pcre-devel
    - pcre 
    - libicu-devel 
    - gcc  
    - gcc-c++ 
    - autoconf  
    - zlib 
    - zlib-devel 
    - glibc 
    - glibc-devel 
    - glib2 
    - glib2-devel 
    - ncurses 
    - ncurses-devel 
    - curl 
    - curl-devel 
    - krb5-devel 
    - libidn 
    - libidn-devel 
    - openldap 
    - openldap-devel 
    - nss_ldap 
    - jemalloc-devel 
    - cmake 
    - boost-devel 
    - bison 
    - automake 
    - libevent 
    - libevent-devel 
    - gd 
    - gd-devel 
    - libtool* 
    - libmcrypt 
    - libmcrypt-devel 
    - mcrypt 
    - mhash 
    - libxslt 
    - libxslt-devel 
    - readline 
    - readline-devel 
    - gmp 
    - gmp-devel 
    - libcurl 
    - libcurl-devel 
    - openjpeg-devel
    - ImageMagick-devel
    - oniguruma-devel
  ignore_errors: true
  when: ansible_os_family == "RedHat"