- name: Install nginx
  become: yes
  hosts: ub22-miro
  vars:
    nginx_version: nginx-1.22.1
    nginx_root_dir: /usr/local/nginx
    nginx_log_dir: /data/logs/nginx
    nginx_pid_file: /var/run/nginx.pid
  roles:
    - nginx