---
- name: Install php
  remote_user: root 
  become: yes
  hosts: tdm-uat-web01
  vars:
    php_version: php-7.2.34
    php_ver: 7.2.34
    php_url: https://www.php.net/distributions/{{ php_version }}.tar.gz
    php_root_dir: /usr/local/php/72
    php_service: php72-fpm
    php_sock_file: "/dev/shm/php72-fpm.sock"
    php_error_log_file: "{{ php_log_dir }}/php72-fpm.log"
    php_slow_log_file: "{{ php_log_dir }}/php72-slow.log"
    redis_version: redis-5.3.7
    imagick_version: imagick-3.7.0
    libiconv_ver: 1.16
    THREAD: 4 
    curl_ver: 7.88.1
    curl_install_dir: /usr/local/curl
    freetype_ver: 2.10.1
    freetype_install_dir: /usr/local/freetype
    argon2_ver: 20171227
    libsodium_ver: 1.0.18
    libzip_ver: 1.2.0
    mhash_ver: 0.9.9.9
  roles:
    - php