---

- include_tasks: php-pre.yml

- include_tasks: "libmcrypt.yml"
  when: php_ver.startswith('7.0.') or php_ver.startswith('7.1.')

- include_tasks: "icu.yml"
  when: php_ver.startswith('7.0.') or php_ver.startswith('7.1.')

- include_tasks: argon2.yml

- include_tasks: freetype.yml

- include_tasks: libcurl.yml

- include_tasks: libiconv.yml

- include_tasks: libsodium.yml

- include_tasks: libzip.yml

- include_tasks: mhash.yml

- include_tasks: "php70-main.yml"
  when: php_ver.startswith('7.0.') or php_ver.startswith('7.1.')

- include_tasks: "php7-main.yml"
  when: php_ver.startswith('7.2.') or php_ver.startswith('7.4.')  

- include_tasks: "php8-main.yml"
  when: php_ver.startswith('8.')

- include_tasks: redis.yml

- include_tasks: imagick.yml

- include_tasks: extend.yml

